/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.byrnadmin;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import kong.unirest.ContentType;
import kong.unirest.HttpResponse;
import kong.unirest.JsonNode;
import kong.unirest.Unirest;
import org.json.JSONObject;

/**
 *
 * @author ilichh1
 */
public class ImageSelector extends javax.swing.JFrame {
    // TODO: Implementar auth correctamente, vamos Mike
    private static final String AUTH_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xOC4yMjQuMTUzLjg2OjgwMDBcL2FwaVwvbG9naW4iLCJpYXQiOjE1NjU3Mjc1NTcsImV4cCI6MTU2NTczMTE1NywibmJmIjoxNTY1NzI3NTU3LCJqdGkiOiJOYmpRdkVUQ1AyTkxIbHRnIiwic3ViIjoxLCJwcnYiOiI4N2UwYWYxZWY5ZmQxNTgxMmZkZWM5NzE1M2ExNGUwYjA0NzU0NmFhIn0.tsKOZj_cbiPL4-_Xd0R3Na1eufHnA2GzfdJoPDz3SVc";

    /**
     * Creates new form ImageSelector
     */
    public ImageSelector() {
        initComponents();
        
        // Test request
        Unirest.get("https://google.com.mx")
                .asJsonAsync(res -> {
                    HttpResponse response = (HttpResponse)res;
                    System.out.println("Status: " + response.getStatus());
                    System.out.println("Response text: " + response.getStatusText());
                });
    }
    
    static HashMap<String, String> createEstateFactory() {
        HashMap<String, String> params = new HashMap<>();
        params.put("name", "Casa de Miguel");
        params.put("description", "La casita humilde de Miguel, decorada con cadaveres de Tlajomulco.");
        params.put("owner_id", "1");
        params.put("estate_type", "1");
        params.put("business_type", "1");
        params.put("comission_or_advertising", "0");
        params.put("surface_area", "100");
        params.put("seller_price", "1000000");
        params.put("latitude", "20.62388600");
        params.put("longitude", "-103.088528");
        params.put("adress", "Calle Mike #69, El Drogo, San Sebastian, Tlajomulco");
        params.put("city_id", "512");
        // params.put("images[]", "");
        return params;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Seleccionar imagenes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 221, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        onSelectImages();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void onSelectImages() {
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showDialog(this, "Seleccionar imagenes") == JFileChooser.APPROVE_OPTION) {
            System.out.println("SELECCIONO IMAGENES EL PTO");
            File sFile = fileChooser.getSelectedFile();
            createEstate(sFile);
        }
    }
    
    private void createEstate(File sFile) {
        // ArrayList<File> filez = new ArrayList<>(Arrays.asList(selectedImages));
        Map<String, Object> hashMap = new HashMap<>();
        hashMap.put("name", "Cancha de futbol");
        hashMap.put("description", "Una humilde canchita en Zapotlanejo.");
        hashMap.put("owner_id", "1");
        hashMap.put("estate_type", "1");
        hashMap.put("business_type", "2");
        hashMap.put("commision_or_advertising", "0");
        hashMap.put("surface_area", "400");
        hashMap.put("seller_price", "1000000");
        hashMap.put("latitude", "20.62388600");
        hashMap.put("longitude", "-103.088528");
        hashMap.put("address", "Alguna dirección en Zapotlanejo");
        hashMap.put("city_id", "1");
        // hashMap.put("images[]", filez);
        JSONObject jsonO = new JSONObject(hashMap);
        // hashMap.put("images[]", filez);
        String url = "http://18.224.153.86:8000/api/estates";
        // String url = "https://ennh0om1nkdo973.m.pipedream.net";
        System.out.println(ContentType.IMAGE_JPEG);
        InputStream is = null;
        try {
            is = new FileInputStream(sFile);
        } catch (FileNotFoundException ex) {
            System.out.println("no is for file");
            Logger.getLogger(ImageSelector.class.getName()).log(Level.SEVERE, null, ex);
        }
        HttpResponse<JsonNode> res = Unirest.post(url)
                .header("Content-Type", "multipart/form-data")
                .header("Accept", "*/*")
                .header("Accept-Encoding", "gzip, deflate")
                // .header("Content-Length", "53361")
                .header("Authorization", "Bearer " + AUTH_TOKEN)
                .queryString(hashMap)
                // .field("images[]", filez)
                .field("images[]", is, ContentType.IMAGE_JPEG, "image.jpg")
                .asJson();
        
        System.out.println("=======");
        System.out.println(res.getStatus());
        System.out.println(res.getStatusText());
        JSONObject json = res.getBody().getObject();
        System.out.println(json.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
